config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  concern :commentable do
    resources :comments
  end

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  concern :image_attachable do
    resources :images, only: %i[create destroy]
  end

  root to: 'gardens#index'
  devise_for :users, controllers: {registrations: "registrations"}
  resources :users do
    resources :avatars, only: %i[create destroy]
    resources :statuses
  end

  resources "contacts", only: [:new, :create]

  resources :gardens, concerns: [:commentable, :image_attachable] do
    resources :favorites, only: %i[create]
  end

  match "contactmail", to: "gardens#contactmail", via: :post
  
  get "/static/landing", to: "static#landing"
  get "/static/landing_map", to: "static#landing_map"
  get "/static", to: "static#landing"
  get "/static/about_us", to: "static#about_us"
  get "/static/gtu", to: "static#gtu"
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  after_create :welcome_send
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :gardens
  has_many :favorites
  has_many :statuses

  validates :first_name, presence: true
  validates :last_name, presence: true

  # For the time being, every user is admin...
  # TODO: seed an admin
  def is_admin?
    self.id.between?(1, 6)
  end

  def find_favorite_gardens
    self.favorites.where(favoritable_type: :Garden).map(&:favoritable).uniq
  end

  private

  has_one_attached :avatar

  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end

end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :authenticate_user!, only: %i[show edit update]
  before_action :correct_user, only: %i[show edit update]

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id].to_i)
    @status = Status.where(user_id: @user.id)
    @favorite_gardens = @user.find_favorite_gardens
  end

  def edit; end

  def update
    @user = User.find(params[:id].to_i)
    @user.update(birthdate: params[:birthdate], description: params[:description], first_name: params[:first_name], last_name: params[:last_name])
    redirect_to user_path(@user)
  end

  private

  def correct_user
    @user = User.find(params[:id].to_i)
    if current_user != @user
      flash[:alert] = "Ce profil n'est pas accessible"
      redirect_to root_path
    end
  end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/users/_signup_modal.html.erb
<div class="modal fade" id="enroute">
  <div class="modal-dialog modal-xl modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Inscription réussie</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="container-fluid">
          <div class="row align-content-center justify-content-center" style="width: 100%">
            <div class="col text-center p-4">
              <h2>Tu peux maintenant…</h2>
            </div>
          </div>
          <div class="row justify-content-center" style="width: 100%">
            <div class="col">
              <%= link_to new_garden_path do %>
              <div class="card" id="create-card">
                <%= image_tag('img-modal-create', style:'width:100%;', class:'card-img-top') %>
                <div class="card-body">
                  <p class="card-text">… créer ton jardin et commencer à parler de tes produits.</p>
                </div>
              </div>
            <% end %>
          </div>
          <!-- /.col-lg-4 -->
          <div class="col">
            <%= link_to root_path do %>
            <div class="card" id="index-card">
              <%= image_tag('img-modal-index', style:'width:100%;', class:'card-img-top') %>
              <div class="card-body">
                <p class="card-text">… explorer et rechercher tous les potagers existants.</p>
              </div>
            </div>
          <% end %>
        </div>
        <!-- /.col-lg-4 -->
      </div>
    </div>
    <div class="modal-footer my-4"></div>
  </div>
</div>
</div>

app/views/users/edit.html.erb
<div class="container-edit">
  <div class="container-form">
    <div class="container-card row justify-content-md-center align-items-center">
      <div class="col col-md-8 col-sm5 col-lg-7 col-xl-7">
        <div class="card border shadow-lg p-4">
          <div class="form-group">
            <h2>
              Dis-nous en plus sur toi
              <i class="em em-deciduous_tree"></i>
            </h2>

            <%=form_tag url_for(action: 'update'), method: "patch" do %>
            <%= label_tag 'Prénom' %>
            <%= text_field_tag 'first_name', @user.first_name, placeholder: 'Prénom*', class:'form-control' %>

            <%= label_tag 'Nom' %>
            <%= text_field_tag 'last_name', @user.last_name, class:'form-control', placeholder: 'Nom*', class:'form-control' %>

            <%= label_tag 'Date de naissance' %>
            <%= text_field_tag 'birthdate', @user.birthdate, placeholder: 'Date de naissance*', class:'form-control' %>
            <br>
            <%= label_tag 'Description' %>
            <%= text_area_tag 'description', @user.description, placeholder: 'Description : Raconte nous ta passion du potager et / ou des légumes !', class:'form-control' %>

            <%= submit_tag "Edite ton profil !", class:"btn submit-btn" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
</div>

app/views/users/new.html.erb
<div class="container-edit">
  <div class="container-form">
    <div class="container-card row justify-content-md-center align-items-center">
      <div class="col col-md-8 col-sm5 col-lg-7 col-xl-7">
        <div class="card border shadow-lg p-4">
          <div class="form-group">
            <h2>Rejoins la communauté
              <i class="em em-deciduous_tree"></i>
            </h2>
            <h4 class="text-center">Étape 2/2 : dis-nous en plus sur toi</i>
          </h4>

          <!-- <form_tag url_for(action: 'update'), method: "patch" do > <form action="/users/30" accept-charset="UTF-8" method="post"> -->
          <%= simple_form_for(@user, html: { method: :patch }) do %>
          <%= label_tag 'Prénom' %>
          <%= text_field_tag 'first_name', @user.first_name, placeholder: 'Prénom*', class:'form-control' %>

          <%= label_tag 'Nom' %>
          <%= text_field_tag 'last_name', @user.last_name, class:'form-control', placeholder: 'Nom*', class:'form-control' %>

          <%= label_tag 'Date de naissance' %>
          <%= text_field_tag 'birthdate', @user.birthdate, placeholder: 'Date de naissance*', class:'form-control' %>
          <br>
          <%= label_tag 'Description' %>
          <%= text_area_tag 'description', @user.description, placeholder: 'Description : Raconte nous ta passion du potager et / ou des légumes !', class:'form-control' %>

          <%= submit_tag "Inscription", class:"btn submit-btn" %>
        <% end %>
      </div>
    </div>
  </div>
</div>
</div>
</div>

app/views/users/show.html.erb
<div class="container">

  <%= stylesheet_link_tag "users" %>

  <div class="card-container border shadow-lg p-4 col-md-8 col-sm-12 col-lg-8">
    <div class="container-pic d-flex user-pic">
      <%if @user.avatar.attached?%>
        <%= image_tag @user.avatar, alt: 'avatar', class:'avatar-user circle-avatar-user' %>
      <% else %>
        <div class="avatar-user circle-avatar-user"></div>
      <% end %>
    </div>

    <% if current_user == @user %>
      <%= form_tag user_avatars_path(@user), multipart: true do %>
      <div class='d-flex align-items-center'>
        <div class="wtf-container d-flex align-self-center">
          <div class="btn btn-large submit-btn-ligth3 btn-file">
            <%if @user.avatar.attached?%>
              Modifie ta photo
            <% else %>
              Rajoute une photo
            <% end %>
            <%= file_field_tag :avatar, onchange: 'this.form.submit();' %>
          </div>
          <div>
          <% end %>
        </div>
      </div>
    </div>
    <div class="show_user_head border-15">
      <% provide(:title, "Profil utilisateur") %><% end %>

      <p class="titre-dark text-center" style="margin:0px;">
        <%= @user.first_name %>
        <%= @user.last_name %></p>
      <p class="text-center" style="margin-bottom:30px;">
        <%= @user.birthdate %></p>
    </div>
    <div class="id-card row">
      <div class="col">
        <div >
          <h2>Présentation</h2>
          <p class="card-text"><%= @user.description %></p>
        </div>
      </div>
      <div class="col">
        <div>
          <h2>Contact</h2>
          <p class="card-text"><%= @user.email %></p>
        </div>
      </div>
    </div>
    <div class="infos-connexion d-flex wrap">
      <%= link_to "Editer mon profil", edit_user_path(@user), class:"btn submit-btn" %>
      <%= link_to "Editer infos de connexion", edit_user_registration_path, class:"btn submit-btn" %>
    </div>
    <div>
      <h2>Favoris</h2>
      <% @favorite_gardens.each do |garden| %>
        <p><%= link_to garden.name, garden_path(garden) %></p>
      <% end %>
    </div>
  </div>

</div>
<%= render "signup_modal" %>
<div id="test"></div>
<script>
  $(document).ready(function () {
    if ('<%= params[:status] %>' == 'new') {
      $('#enroute').modal('toggle');
    };
  });
</script>
</div>