config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  concern :commentable do
    resources :comments
  end

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  concern :image_attachable do
    resources :images, only: %i[create destroy]
  end

  root to: 'gardens#index'
  devise_for :users, controllers: {registrations: "registrations"}
  resources :users do
    resources :avatars, only: %i[create destroy]
    resources :statuses
  end

  resources "contacts", only: [:new, :create]

  resources :gardens, concerns: [:commentable, :image_attachable] do
    resources :favorites, only: %i[create]
  end

  match "contactmail", to: "gardens#contactmail", via: :post
  
  get "/static/landing", to: "static#landing"
  get "/static/landing_map", to: "static#landing_map"
  get "/static", to: "static#landing"
  get "/static/about_us", to: "static#about_us"
  get "/static/gtu", to: "static#gtu"
end

app/models/garden.rb
# frozen_string_literal: true

class Garden < ApplicationRecord
  belongs_to :user
  has_many :products
  has_many :comments
  has_many :favorites, as: :favoritable

  validates :name, length: { in: 5..150 }
  validates :zipcode, presence: true, format: { with: /(([0-8][0-9])|(9[0-5]))[0-9]{3}\z/ }
  has_many_attached :images

  geocoded_by :full_address
  after_validation :geocode, if: ->(obj) { obj.adress.present? && obj.adress_changed? }

  def self.search(search)
    if search
      result = []
      result << where(["adress LIKE ?", "%#{search}%"])
      result << where(["name LIKE ?", "%#{search}%"])
      result << where(["city LIKE ?", "%#{search}%"])
      result << where(["country LIKE ?", "%#{search}%"])
      result << where(["zipcode LIKE ?", "%#{search}%"])

      Product.where(["name LIKE ?", "%#{search}%"]).each do |product|
        result << Garden.where(id: product.garden_id)
      end

      final_result = result.map do |collection|
        collection.map(&:itself)
      end
      @search_result = final_result.flatten.uniq
    else
      all
    end

  end



  private

  def full_address
    [adress, zipcode, city, country].compact.join(", ")
  end
end

app/controllers/gardens_controller.rb
# frozen_string_literal: true

# app/controllers/gardens_controller.rb
class GardensController < ApplicationController
  before_action :set_garden, only: %i[show]
  before_action :authenticate_user!, only: %i[show new create edit update]
  before_action :correct_user, only: %i[edit update]
  before_action :connected_user, only: %i[show new]

  def index
    redirect_to static_landing_path unless user_signed_in?
    @search = helpers.evaluate_search_result(params[:search])

    # TODO: decide if update_at better
    @gardens = Garden.order(created_at: :desc).page(params[:page]).per(6)

    @hash = GenerateMapForIndex.new(@search).perform
    @status = Status.last(3).sort_by(&:updated_at).reverse
  end

  # TODO: rename @nearby to @nearbies
  # TODO: rename @hash
  def show
    @comments = @garden.comments.order created_at: :desc
    @user = @garden.user
    @nearby = helpers.locate_nearby_gardens(@garden)
    @hash = GenerateMapForShow.new(@garden, @nearby).perform

    @products = @garden.products
    # TODO: from find_by to .last/.first or get an array
    @status = Status.find_by(user_id: @garden.user_id)

    @how_many_days = (Time.now - @status.updated_at) / 86_400 * 10 if @status
  end

  def new
    @user = current_user
  end

  def create
    User.find(current_user.id).update(first_name: params[:userfirstname], last_name: params[:userlastname])

    @garden = Garden.new(user_id: current_user.id, name: params[:gardenname], adress: params[:adress], city: params[:city], zipcode: params[:zipcode], country: params[:country])
    if @garden.save
      flash.now[:success] = 'Potager bien enregistré !'
      redirect_to garden_path @garden
    else
      flash.now[:warning] = 'Ooops...'
      render :new
    end

    Product.create(name: params[:productname1], garden_id: Garden.last.id)
    Product.create(name: params[:productname2], garden_id: Garden.last.id)
    Product.create(name: params[:productname3], garden_id: Garden.last.id)
    Product.create(name: params[:productname4], garden_id: Garden.last.id)
    Product.create(name: params[:productname5], garden_id: Garden.last.id)
  end

  def edit
    @garden = Garden.find_by(user_id: current_user.id)
    @products = @garden.products
  end

  def update
    @garden = Garden.find_by(user_id: current_user.id)
    @products = @garden.products

    @garden.update(name: params[:gardenname], adress: params[:adress], city: params[:city], zipcode: params[:zipcode], country: params[:country])

    @products[0].update(name: params[:productname1])
    @products[1].update(name: params[:productname2])
    @products[2].update(name: params[:productname3])
    @products[3].update(name: params[:productname4])
    @products[4].update(name: params[:productname5])

    redirect_to garden_path(@garden)
  end

  def destroy; end

  def contactmail
    UserContactMailer.contact_garden(params).deliver_now
  end

  private

  def set_garden
    @garden = Garden.find(params[:id])
  end

  def correct_user
    @garden = Garden.find(params[:id])
    if current_user.nil?
      flash[:alert] = "Vous ne me semblez pas connecté"
      redirect_to new_user_registration_path
    elsif current_user != @garden.user
      flash[:alert] = "Ce jardin n'est pas accessible"
      redirect_to root_path
    end
  end

  def connected_user
    if current_user.nil?
      flash[:alert] = "Vous ne me semblez pas connecté"
      redirect_to new_user_registration_path
    end
  end
end

app/helpers/gardens_helper.rb
# frozen_string_literal: true

module GardensHelper
  include Rails.application.routes.url_helpers

  def evaluate_search_result(search_params)
    @results = Garden.search(search_params)
    if @results.empty?
      flash.now[:warning] = "Cette recherche n'a pas donné de résultats"
      return Garden.all
    else
      return @results
    end
  end
  
  def locate_nearby_gardens(location)
    @garden = location
    @garden.nearbys(20)
  end

  def locate_closest_gardens(location)
    @distance_array = [5, 10, 20, 50, 100]
    @location = location
    @closest = []
    i = 0
    until @closest.length >= 3
      @distance = @distance_array[i]
      @closest = Garden.near(@location.coordinates, @distance)
      i = i + 1
      if i == @distance_array.length
        return [@distance, [@location]]
      end
    end
    return [@distance, @closest]
  end

  def locate_by_zipcode(location)
    @search = Geocoder.search(location).select{ |location| location.country == "France"}.first
    if @search.nil?
      flash.now[:warning] = "Code postal non reconnu"
      return nil
    elsif @search.country != "France"
      flash.now[:warning] = "Code postal non existant en France (#{@search.country})"
      return nil
    else
      locate_closest_gardens(@search)
    end
  end

  def set_landing_map_message(integer)
    integer = integer - 1
    if integer == 0
      "Il n'y a pas encore de potager du coin, crée le premier !"
    elsif integer == 1
      "Tu as 1 potager à proximité, rejoins-le !"
    elsif integer >= 2
      "Tu as #{integer} potagers à proximité, rejoins-les !"
    else
      "(You should not see this message...)"
    end
  end
end

app/views/gardens/_index_gardens_cards.html.erb
<div class="card-garden-title d-flex align-content-between justify-content-center flex-wrap">
	<h1>Tous les potagers</h1>
</div>

<div class="d-flex align-content-between justify-content-center flex-wrap">
	<% @gardens.each do |garden| %>
		<div class="card space-gardens">
			<div class="card-image">
				<%if garden.images.attached?%>
					<%= image_tag(garden.images.first, class:'card-img-top') %>
				<% else %>
					<%= image_tag 'slide-2.jpg', class:'card-img-top' %>
				<% end %>
			</div>
			<div class="d-flex justify-content-center flex-column">
				<h2 class='align-self-center'><%=link_to garden.name, garden_path(garden.id) %></h2>
				<p class='align-self-center'><%= garden.city %></p>
				<p class='align-self-center'>
					<% if garden.user.statuses.any? %>
						<p class="status-cards-index">
							<span class='para-strong'>Statut</span>
							: "<%= garden.user.statuses.last.content %>"</p>
					<% end %>
				</p>
				<%= link_to "Voir le jardin", garden_path(garden), class:"btn btn-light" %>
			</div>
		</div>
	<% end %>
</div>
<div class="d-flex align-content-between justify-content-center flex-wrap">
	<%= paginate(@gardens) %>
</div>

app/views/gardens/_map.html.erb
<div class="map" id="GardenMap" style="width:600px;height:300px;">

</div>
<script>
handler = Gmaps.build('Google');
handler.buildMap({ provider: {}, internal: {id: 'GardenMap'}}, function(){
  markers = handler.addMarkers(<%=raw @hash.to_json %>);
  handler.bounds.extendWith(markers);
  handler.fitMapToBounds();
});
</script>

app/views/gardens/_map_for_index.html.erb
<div class="map" id="GardenMap" style="width:600px;height:400px;"></div>

<script>
  handler = Gmaps.build('Google');
  handler.buildMap({
    provider: {},
    internal: {
      id: 'GardenMap'
    }
  }, function () {
    markers = handler.addMarkers(<%=raw @hash.to_json %>);
    handler.bounds.extendWith(markers);
    handler.fitMapToBounds();
  });
</script>

app/views/gardens/_map_for_show.html.erb
<div class="col-lg-12" id="GardenMap"></div>

<script>
  handler = Gmaps.build('Google');
  handler.buildMap({
    provider: {},
    internal: {
      id: 'GardenMap'
    }
  }, function () {
    markers = handler.addMarkers(<%=raw @hash.to_json %>);
    handler.bounds.extendWith(markers);
    handler.fitMapToBounds();
    if (handler.getMap().getZoom() > 12) {
      handler.getMap().setZoom(12);
    }
  });
</script>

app/views/gardens/_map_info_index.html.erb
<span style="font-weight: bold"><%= garden.name %></span><br />
<%= garden.zipcode %> <%= garden.city %><br />
<%= garden.country %><br />
<!-- "link_to" tag here doesn't work -->
  <em><a href="gardens/<%= garden.id %>">Voir la fiche</a></em>

app/views/gardens/_map_info_show.html.erb
<span style="font-weight: bold"><%= garden.name %></span><br />
<%= garden.zipcode %> <%= garden.city %><br />
<!-- "link_to" tag here doesn't work -->
<em><a href="<%= garden.id %>">Voir la fiche</a></em>

app/views/gardens/_map_info_show_self.html.erb
<span style="font-weight: bold"><%= garden.name %></span><br />
<%= garden.zipcode %> <%= garden.city %><br /><br />
<div class="text-center" style="font-weight: bold">TU ES ICI! <i class="fa fa-smile-o" aria-hidden="true"></i></div>

app/views/gardens/_research.html.erb
<form>
  <div class="col-4 col-md-5 col-lg-4 nav-research">
    <div class="form-row">
      <div>
        <i class="fa fa-search" aria-hidden="true"></i>
        <%= form_for(@gardens) do %>
        <%= text_field :search, params[:search] %>
        <%= submit "Go !", :name => nil %>
      <% end %>
    </div>
  </div>
</div>
</form>

app/views/gardens/_status_index.html.erb
<div class="container">
  <div class="container-status ">
    <h1>
      L'actu des potagers !
    </h1>
    <div>
      <div class="status-i">

        <% @status.each do |status| %>

          <div class="one-status">
            <div class="d-flex align-items-center">
              <%if status.user.avatar.attached?%>
                <div><%= image_tag status.user.avatar, alt: 'avatar', class:'circle-avatar-user-status' %></div>
              <% end %>
              <div id="cercle"></div>
              <p class="title-status">
                <%= link_to status.content, garden_path(status.user.gardens.last) %></p>
            </div>

            <p class="first-name-status">Par
              <%= status.user.first_name %></p>
            <p >
              <% @date = ((Time.now - status.updated_at) / 86400 * 10).to_i %>
                <% if @date == 0 %>
                  <p class="date-status">Posté aujoud'hui</p>
                  <% elsif @date == 1 %>
                    <p class="date-status">Posté hier</p>
                  <% else %>
                    <p class="date-status">Il y a
                      <%= @date %>
                      jours</p>
                  <% end %>
                </div>
              <% end %>

            </div>
          </div>
        </div>
      </div>

app/views/gardens/edit.html.erb
<div class="container">
  <div class="container-form">
    <div class="container-card row justify-content-md-center align-items-center">
      <div class="col col-md-8 col-sm5 col-lg-7 col-xl-7">
        <div class="card border shadow-lg p-4">
          <h2>
            Modifie ton potager !
          </h2>
          <div class="form-inputs">
            <%=form_tag url_for(action: 'update'), method: "patch" do %>
            <%= label_tag 'Nom de ton potager' %>
            <%= text_field_tag 'gardenname', @garden.name, class:'form-control' %>

            <%= label_tag 'Adresse de ton potager' %>
            <%= text_field_tag 'adress', @garden.adress, class: 'form-control'%>

            <%= label_tag 'Adresse de ton potager' %>
            <%= text_field_tag 'zipcode', @garden.zipcode, class:'form-control'%>
            <br/>

            <%= label_tag 'Adresse de ton potager' %>
            <%= text_field_tag 'city', @garden.city, class:'form-control'%>
            <br/>

            <%= label_tag 'Adresse de ton potager' %>
            <%= text_field_tag 'country', @garden.country, class:'form-control'%>
            <br/>
            <br/>
            <p>Nom du Produit:</p>
            <%= text_field_tag 'productname1', @products[0].name , class:'form-control' %>
            <br/>
            <p>Nom du Produit:</p>
            <%= text_field_tag 'productname2', @products[1].name, class:'form-control' %>
            <br/>
            <p>Nom du Produit:</p>
            <%= text_field_tag 'productname3', @products[2].name, class:'form-control' %>
            <br/>
            <p>Nom du Produit:</p>
            <%= text_field_tag 'productname4', @products[3].name, class:'form-control' %>
            <br/>
            <p>Nom du Produit:</p>
            <%= text_field_tag 'productname5', @products[4].name, class:'form-control' %>
            <div class="form-actions">
              <%= submit_tag "Edite ton potager !", class:"btn submit-btn" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
</div>

app/views/gardens/index.html.erb
<div class="d-flex justify-content-center flex-wrap">
  <%= form_tag gardens_path, method: :get do %>
  <%= text_field_tag :search, params[:search], placeholder: 'Carottes, Paris', class: "btn bg-light text-left m-2 p-2" %>
  <%= button_tag type: 'submit', class: 'col-1 btn btn-yeah2 my-2 p-2' do %>
  <i class="fa fa-search" aria-hidden="true"></i>
<% end %>
<% end %>
</div>
<div class="col">
<%= render 'static/map_for_landing' %>
</div>
<div>
<%= render 'gardens/status_index' %>
<%= render 'gardens/index_gardens_cards' %>
</div>

app/views/gardens/new.html.erb
<div class="container-new-garden">
	<div class="container-card row justify-content-md-center align-items-center">
		<div class="col col-md-8 col-sm5 col-lg-5 col-xl-4">
			<div class="card border shadow-lg p-4">
				<h2>
					Créé ton potager !
				</h2>
				<div class="form-inputs">
					<%=form_tag url_for(action: 'create'), method: "post" do %>

					<%= label_tag 'Nom de ton potager' %>
					<%= text_field_tag 'gardenname', @gardenname, placeholder: 'Nom de ton potager', class:'form-control' %>

					<%= label_tag 'Adresse de ton potager' %>
					<%= text_field_tag 'adress', @adress, placeholder: 'Adresse de ton potager', class:'form-control' %>

					<%= label_tag 'Code Postal' %>
					<%= text_field_tag 'zipcode', @zipcode, class:'form-control', placeholder: 'Code postal' %>

					<%= label_tag 'Adresse de ton potager' %>
					<%= text_field_tag 'city', @city, class:'form-control', placeholder: 'Ville'%>

					<%= label_tag 'Adresse de ton potager' %>
					<%= text_field_tag 'country', @country, class:'form-control' , placeholder: 'Pays', default: 'France' %>
					<br/><br/>

					<h2>Tu peux ajouter jusqu'à 5 types de produits :</h2>
					<p class='productname'>Nom du produit 1 :</p>
					<%= text_field_tag 'productname1', "   ", class:'form-control' %>

					<p class='productname'>Nom du produit 2 :</p>
					<%= text_field_tag 'productname2', "   ", class:'form-control'%>

					<p class='productname'>Nom du produit 3 :</p>
					<%= text_field_tag 'productname3', "   ", class:'form-control' %>

					<p class='productname'>Nom du produit 4 :</p>
					<%= text_field_tag 'productname4', "   ", class:'form-control' %>

					<p class='productname'>Nom du produit 5 :</p>
					<%= text_field_tag 'productname5', "   ", class:'form-control' %>

					<%= submit_tag "Créer ton potager", class:"btn submit-btn" %>

				<% end %>
			</div>
		</div>

	</div>
</div>
</div>

app/views/gardens/search.html.erb
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <%= image_tag('slide1', width:'100%', class:'d-block w-100') %>
    </div>
    <div class="carousel-item">
      <%= image_tag('slide2', width:'100%', class:'d-block w-100') %>
    </div>
    <div class="carousel-item">
      <%= image_tag('slide3', width:'100%', class:'d-block w-100') %>
    </div>
    <div class="carousel-caption d-none d-md-block">
      <h2>Mon Potager</h2>
      <p>Vendez ou troquez le surplus de votre potager !</p>
    </div>
  </div>

  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

<%= render 'gardens/index_gardens_cards' %>

<div class="container">
  <div class="row">

    <div class="col gardens-list">
      <ul class="list-group">
        <% @search.each do |garden| %>
          <li class="list-item">
            <%= link_to garden.name, garden_path(garden) %>
          </li>
        <% end %>

      </ul>

    </div>
    <div class="col">
      <%= render 'map_for_index' %>
    </div>
  </div>
</div>

<div class="main-status">
  <div class="container-status">
    <div class="status-i">
      <h1>
        Fil d'actualité
      </h1>

      <% @status.each do |status| %>
        <div class="one-status">
          <p class="para-strong"><%= link_to status.content, garden_path(status.user.gardens.last) %></p>
          <p>Par
            <%= status.user.first_name %></p>
          <% @date = ((Time.now - status.updated_at) / 86400 * 10).to_i %>
            <% if @date == 0 %>
              <p>Posté aujoud'hui</p>
              <% elsif @date == 1 %>
                <p>Posté hier</p>
              <% else %>
                <p>Il y a
                  <%= @date %>
                  jours</p>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>

app/views/gardens/show.html.erb
<div class="container">
  <%= stylesheet_link_tag "gardens" %>
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">

  <div class="content-garden">
    <div class="row">
      <div class="col col-sm-12 col-md-12 col-lg-7">
        <div class="div-status">
          <div class="">
            <h1>
              <%= @garden.name %>
            </h1>
          </div>
          <div class="gardens-update-btn col-lg-7">
            <% if current_user == @user %>
              <span style="margin:0 10px 0 -15px"><%=link_to "Editer le potager", edit_garden_path(@garden), class:"btn submit-btn-ligth"%></span>
              <%= link_to 'Nouveau statut', new_user_status_path(@user), class:"btn submit-btn-ligth" %>
            <% end %>
          </div>
          <% if @status.nil? %>
            <div class="status-user">
              <div id="cerclejaune"></div>
              <%= "Pas de status pour ce jardin" %>
            <% else %>

              <div class="status-user">

                <div id="cercle" style="margin: 35px 0 0 0"></div>
                <p class="para-strong status-content" style="margin: 20px 20px 0px 15px">
                  <%= @status.content %>
                  <% if current_user == @user %><% end %>
                  <span style="margin-left:10px"><%= link_to 'Voir tous les statuts', user_statuses_path(@user) %></span>
                </div>

                <div class="howmanydays">
                  <% if @how_many_days.to_i == 1 %>
                    <p class="para-small">Posté hier</p>

                    <% elsif @how_many_days.to_i == 0 %>
                      <p class="para-small">Posté aujourd'hui</p>

                    <% else %>
                      <p class="para-small">Il y a
                        <%= @how_many_days.to_i %>
                        jours</p>
                    <% end %>
                  <% end %>
                </div>
              </div>
              <div>
                <% @garden.images.each do |image| %>
                  <%= image_tag(image, alt: 'garden_image', class:'avatar-garden') %>
                <% end %>
                <% if current_user == @user %>
                  <%= form_tag garden_images_path(@garden), multipart: true do %>
                  <% if @garden.images.attached? %>
                    <span class="btn btn-large submit-btn-ligth btn-file" style="margin-top:-40px">
                      Rajoute une photo
                    <% else %>
                      <span class="btn btn-large btn-file btn-file-hover">
                        <%= image_tag('img-default.jpg', alt: 'garden_image', class:'avatar-garden', style:"margin:0") %>
                      <% end %>
                      <%= file_field_tag :images, onchange: 'this.form.submit();' %>
                    </span>
                  <% end %>
                  <%if @garden.images.attached? %>
                    <%= form_tag garden_image_path(@garden), method: "delete", style: "display: inline" do %>
                    <%= submit_tag "Supprimer les images", class:"btn submit-btn-ligth3" %>
                  <% else %>
                  <% end %>
                <% end %>
              <% end %>
            </div>

            <div class="products-garden">
              <h1>Les Produits
                <a></h1>
                <div class="legumes-garden">
                  <div class="legumes-list">
                    <% @products.each do |h| %>
                      <p>
                        <%= h.name %>
                      </p>
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
            <div class="col col-sm-12 col-md-12 col-lg-5">
              <div class="gardenshow-2">
                <div class="container-pic d-flex">
                  <%if @user.avatar.attached? %>
                    <%= image_tag @user.avatar, alt: 'avatar', class:'avatar-user circle-avatar-user' %>
                  <% else %>
                    <div class="avatar-user circle-avatar-user"></div>
                  <% end %>
                </div>
                <div class="name-usergarden">
                  <% if @user.first_name.nil? %>
                    <p>
                      <%= link_to "Utilisateur Anonyme", user_path(@user), class:"titre-dark"%>
                    </p>
                  <% else %>
                    <p class="titre-dark">
                      <%= (@user.first_name + " " + @user.last_name)%>
                    </h1>
                  <% end %>
                  <p class="interlign-name">
                    <%= @garden.adress %>
                  </p>
                </div>
                <div class="description-usergarden">
                  <p class="titre-dark text-center" style="margin: 0">Présentation</p>
                  <p class="text-center" style="padding:0px 30px 0 30px">
                    <%= @user.description %>
                  </p>
                </div>
                <div class="send-message" style="margin:50px 0 0 0">
                  <%= link_to "Envoyer un message", "#modal", class: 'btn submit-btn', "data-toggle": "modal" %>
                </div>
              </div>
            </div>
          </div>
        </div>
        <h1 style="margin: 30px 0 20px 0">Sur la carte</h1>
        <div class=" col-lg-12">
          <div class="col">
            <%= render 'static/map_for_landing' %>
          </div>
        </div>

        <div class="favorite-button ">
          <span><%= link_to "Ajouter ce jardin en favoris", garden_favorites_path(@garden), method: :post, class:"btn submit-btn2 col col-sm-12 col-md-12 col-lg-12 col-xl-12"%></span>
        </div>

        <div class="card col-lg-12 comment-content">
          <ul class="list-group list-group-flush">
            <% @comments.each do |com| %>
              <li class="list-group-item">
                <p class='para-strong'><%= (com.user.first_name + " " + com.user.last_name) %></p>
                <%= com.content %>
              </li>
              <% if current_user == com.user %>
                <%= link_to "Supprimer" , garden_comment_path(@garden, com.id), method: 'delete', class:"btn btn-light col-md-2" %>
              <% end %>
            <% end %>
          </ul>
        </div>
        <div class=" card-header col col-lg-12">
          <div class="">
            <h3>
              Ajouter un commentaire
            </h3>
            <%=form_tag garden_comments_path(@garden), method: "post" do %>
            <%= label_tag 'Content' %>
            <%= text_area_tag 'content', @content, class:'form-control' %>
            <%= hidden_field_tag(:id, @garden.id) %>
            <br/>
            <%= submit_tag "Commenter", class:"btn submit-btn-ligth"%>
          <% end %>
        </div>
      </div>
      <div id="modal" class="modal hide fade" tabindex="-1" role="dialog" title="Envoyer un message">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title">
                <% image_tag "logo", style:"width=100px;" %>
                  Envoyer un message</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-body">
                <%= form_with(url: contactmail_path, id: 'msg-form') do |f| %>
                <%= f.hidden_field :garden_id, value: @garden.id %>
                <%= f.hidden_field :current_user_id, value: current_user.id %>
                <div class="form-group">
                  <label for="subject">Objet</label>
                  <%= f.text_field :subject, id: "subject", class: 'form-control p-2', placeholder: "Objet du message", :required => true %>
                </div>
                <div class="form-group">
                  <label for="message">Message</label>
                  <%= f.text_field :message, id: "message", class: 'form-control p-2', placeholder: "Texte du message", :required => true %>
                </div>
              </br>
              <%= button_tag type: 'button', class: 'btn submit-btn-ligth my-2 p-2', "data-dismiss": "modal" do %>
              Annuler
            <% end %>
            <%= button_tag type: 'submit', class: 'btn submit-btn my-2 p-2', id: 'send-btn' do %>
            Envoyer
          <% end %>
        <% end %>
      </div>
      <div class="modal-footer"></div>
    </div>
  </div>
</div>
</div>

<script>
$(document).ready(function () {
  $('#send-btn').mouseup(function () {
    $('#modal').modal('toggle');
  });
});
</script>