config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  concern :commentable do
    resources :comments
  end

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  concern :image_attachable do
    resources :images, only: %i[create destroy]
  end

  root to: 'gardens#index'
  devise_for :users, controllers: {registrations: "registrations"}
  resources :users do
    resources :avatars, only: %i[create destroy]
    resources :statuses
  end

  resources "contacts", only: [:new, :create]

  resources :gardens, concerns: [:commentable, :image_attachable] do
    resources :favorites, only: %i[create]
  end

  match "contactmail", to: "gardens#contactmail", via: :post
  
  get "/static/landing", to: "static#landing"
  get "/static/landing_map", to: "static#landing_map"
  get "/static", to: "static#landing"
  get "/static/about_us", to: "static#about_us"
  get "/static/gtu", to: "static#gtu"
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
# frozen_string_literal: true

class Comment < ApplicationRecord
  belongs_to :garden
  belongs_to :user
end

app/models/favorite.rb
# frozen_string_literal: true

class Favorite < ApplicationRecord
  belongs_to :user, dependent: :destroy
  belongs_to :favoritable, polymorphic: true, dependent: :destroy
end

app/models/garden.rb
# frozen_string_literal: true

class Garden < ApplicationRecord
  belongs_to :user
  has_many :products
  has_many :comments
  has_many :favorites, as: :favoritable

  validates :name, length: { in: 5..150 }
  validates :zipcode, presence: true, format: { with: /(([0-8][0-9])|(9[0-5]))[0-9]{3}\z/ }
  has_many_attached :images

  geocoded_by :full_address
  after_validation :geocode, if: ->(obj) { obj.adress.present? && obj.adress_changed? }

  def self.search(search)
    if search
      result = []
      result << where(["adress LIKE ?", "%#{search}%"])
      result << where(["name LIKE ?", "%#{search}%"])
      result << where(["city LIKE ?", "%#{search}%"])
      result << where(["country LIKE ?", "%#{search}%"])
      result << where(["zipcode LIKE ?", "%#{search}%"])

      Product.where(["name LIKE ?", "%#{search}%"]).each do |product|
        result << Garden.where(id: product.garden_id)
      end

      final_result = result.map do |collection|
        collection.map(&:itself)
      end
      @search_result = final_result.flatten.uniq
    else
      all
    end

  end



  private

  def full_address
    [adress, zipcode, city, country].compact.join(", ")
  end
end

app/models/product.rb
# frozen_string_literal: true

class Product < ApplicationRecord
  belongs_to :garden

  validates :name, length: { in: 3..50 }
end

app/models/status.rb
# frozen_string_literal: true

class Status < ApplicationRecord
  belongs_to :user

  validates :content, length: { in: 6..1000 }
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  after_create :welcome_send
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :gardens
  has_many :favorites
  has_many :statuses

  validates :first_name, presence: true
  validates :last_name, presence: true

  # For the time being, every user is admin...
  # TODO: seed an admin
  def is_admin?
    self.id.between?(1, 6)
  end

  def find_favorite_gardens
    self.favorites.where(favoritable_type: :Garden).map(&:favoritable).uniq
  end

  private

  has_one_attached :avatar

  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end

end

app/controllers/images_controller.rb
# frozen_string_literal: true

class ImagesController < ApplicationController
  def create
    @garden = Garden.find(params[:garden_id])
    @garden.images.attach(params[:images])
    redirect_to(garden_path(@garden))
  end

  def destroy
    @garden = Garden.find(params[:garden_id])
    @images = @garden.images
    @images.each do |image|
      image.purge
      redirect_to garden_path(@garden)
    end
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def landing
    @gardens = Garden.all
    @search_by_zipcode = ''
    unless params[:search_near].nil?
      zipcode = params[:search_near]
      @search_by_zipcode = helpers.locate_by_zipcode(zipcode)
      unless @search_by_zipcode.nil?
        @hash = GenerateMapForLanding.new(@search_by_zipcode[1]).perform
        @landing_map_message = helpers.set_landing_map_message(@search_by_zipcode[1].length)
        render 'landing_map'
      end
    end
  end

  def landing_map; end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :authenticate_user!, only: %i[show edit update]
  before_action :correct_user, only: %i[show edit update]

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id].to_i)
    @status = Status.where(user_id: @user.id)
    @favorite_gardens = @user.find_favorite_gardens
  end

  def edit; end

  def update
    @user = User.find(params[:id].to_i)
    @user.update(birthdate: params[:birthdate], description: params[:description], first_name: params[:first_name], last_name: params[:last_name])
    redirect_to user_path(@user)
  end

  private

  def correct_user
    @user = User.find(params[:id].to_i)
    if current_user != @user
      flash[:alert] = "Ce profil n'est pas accessible"
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
    def flash_class(level)
      case level
          when 'notice' then "alert alert-primary alert-info alert-dismissible fade show"
          when 'success' then "alert alert-primary alert-success alert-dismissible fade show"
          when 'warning' then "alert alert-primary alert-warning alert-dismissible fade show"
          when 'alert' then "alert alert-primary alert-error alert-dismissible fade show"
      end
    end

    def full_title(page_title = '')
      base_title = "MonPotager"
      if page_title.empty?
        base_title
      else
        page_title + " | " + base_title
      end
    end
  
end

app/helpers/avatars_helper.rb
# frozen_string_literal: true

module AvatarsHelper
end

app/helpers/comments_helper.rb
# frozen_string_literal: true

module CommentsHelper
end

app/helpers/favorites_helper.rb
# frozen_string_literal: true

module FavoritesHelper
end

app/helpers/gardens_helper.rb
# frozen_string_literal: true

module GardensHelper
  include Rails.application.routes.url_helpers

  def evaluate_search_result(search_params)
    @results = Garden.search(search_params)
    if @results.empty?
      flash.now[:warning] = "Cette recherche n'a pas donné de résultats"
      return Garden.all
    else
      return @results
    end
  end
  
  def locate_nearby_gardens(location)
    @garden = location
    @garden.nearbys(20)
  end

  def locate_closest_gardens(location)
    @distance_array = [5, 10, 20, 50, 100]
    @location = location
    @closest = []
    i = 0
    until @closest.length >= 3
      @distance = @distance_array[i]
      @closest = Garden.near(@location.coordinates, @distance)
      i = i + 1
      if i == @distance_array.length
        return [@distance, [@location]]
      end
    end
    return [@distance, @closest]
  end

  def locate_by_zipcode(location)
    @search = Geocoder.search(location).select{ |location| location.country == "France"}.first
    if @search.nil?
      flash.now[:warning] = "Code postal non reconnu"
      return nil
    elsif @search.country != "France"
      flash.now[:warning] = "Code postal non existant en France (#{@search.country})"
      return nil
    else
      locate_closest_gardens(@search)
    end
  end

  def set_landing_map_message(integer)
    integer = integer - 1
    if integer == 0
      "Il n'y a pas encore de potager du coin, crée le premier !"
    elsif integer == 1
      "Tu as 1 potager à proximité, rejoins-le !"
    elsif integer >= 2
      "Tu as #{integer} potagers à proximité, rejoins-les !"
    else
      "(You should not see this message...)"
    end
  end
end

app/helpers/images_helper.rb
# frozen_string_literal: true

module ImagesHelper
end

app/helpers/products_helper.rb
# frozen_string_literal: true

module ProductsHelper
end

app/helpers/registrations_helper.rb
# frozen_string_literal: true

module RegistrationsHelper
end

app/helpers/statuses_helper.rb
# frozen_string_literal: true

module StatusesHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/contacts/create.html.erb
<div>
  <% flash.each do |key, value| %>
    <div>
      <a href="#" data-dismiss="alert">×</a>
        <%= value %>
    </div>
  <% end %>
</div>

app/views/contacts/new.html.erb
<div class="row justify-content-md-center p-4" style="margin-top:200px;">
  <div class="col-md-6">
    <div align="center">
      <h3>Envoyez un message à
        <%= @garden.name %></h3>

      <%= simple_form_for @contact, html: {class: 'form' } do |f| %>
      <%= f.input :garden, as: :hidden %>
      <%= f.input :user, as: :hidden %>
      <%= f.input :subject, :as => :text, :required => true %>
      <%= f.input :message, :as => :text, :required => true %>
      <div class="hidden">
        <%= f.input :nickname, :hint => 'Leave this field blank!' %>
      </div>
      <div>
        <br>
        <%= f.button :submit, 'Send message', :class=> "btn btn-primary" %>
      </div>
    <% end %>
  </div>
</div>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">

  <div class="footer-container row">
    <div class="reverse-logo col col-12 col-sm-12 col-md-4 col-lg-4">
      <%= link_to(image_tag('logo-white', class: 'w-75'), root_path) %>
    </div>
    <div class="links col col-12 col-sm-12 col-md-4 col-lg-4">
      <ul>
        <li>
          <%= link_to "A propos", static_about_us_path, style: "color: white;" %></li>
        <li>
          <%= link_to "CGU", static_gtu_path, style: "color: white;" %></li>
        <% if user_signed_in? && current_user.is_admin? %>
          <li><%= link_to "Administration", rails_admin_path, style: "color: white;" %></li>
        <% end %>
      </ul>
    </div>
    <div class="social-media col col-12 col-sm-12 col-md-4 col-lg-4">
      <div class="icons ">
        <a href="https://www.facebook.com/Mon-Potager-424363834981158" target="_blank">
          <i class="fab fa-facebook-f"></i>
        </a>
        <a href="https://www.instagram.com/monpotager8/" target="_blank">
          <i class="fab fa-instagram"></i>
        </a>
        <a href="https://twitter.com/MonPotager3" target="_blank">
          <i class="fab fa-twitter"></i>
        </a>
        <a href="mailto:monpotagerbiz@gmail.com">
          <i class="far fa-envelope"></i>
        </a>
      </div>
    </div>
  </div>

</footer>

app/views/layouts/_navbar.html.erb
<nav class="homepage">
  <div class="navbar">
    <div class="col-12 col-md-4 col-lg-4">
      <%= link_to (image_tag('logo', width:'60%')), root_path %>
    </div>
    <div class="connexion-info" style='margin-right:50px;'>
      <% if user_signed_in?  %>
        <% if !current_user.gardens.empty? %>
        <% else %>
          <div class="col-sm-12 col-md-6 col-lg-auto">
            <%= link_to 'Créer mon potager', new_garden_path, class: "noHover button-1" %>
          </div>
        <% end %>
      <% end %>
      <li class="dropdown col-sm-12 col-md-6 col-lg-auto">
        <h2 class="dropdown-toggle noHover button-2" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
          Menu
          <span class="caret"></span>
        </h2>
        <ul class="dropdown-menu" style="flex-wrap:no-wrap; min-width: 200px;" aria-labelledby="dropdownMenu1">
          <% if user_signed_in?  %>
            <% if !current_user.gardens.empty? %>
              <li>
                <p style='font-size:18px'><%= link_to 'Voir mon potager', garden_path(current_user.gardens.last.id), class: "" %></p>
              </li>
            <% end %>
            <li>
              <p style='font-size:18px'><%= link_to "Mon profil", user_path(current_user), class: "" %></p>
            </li>
            <li>
              <p style='font-size:18px'><%= link_to "Deconnexion",destroy_user_session_path, method: :delete, class: "" %></p>
            </li>
          <% else %>
            <li>
              <p style='font-size:18px'><%= link_to "Me connecter", new_user_session_path, class: " noHover" %></p>
            </li>
            <li>
              <p style='font-size:18px'><%= link_to "M'inscrire", new_user_registration_path, class: "noHover" %></p>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mon Potager - Les potagers autour de chez toi !</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= favicon_link_tag asset_path('favicon.png') %>
    <link href="https://afeld.github.io/emoji-css/emoji.css" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    <script src="//maps.google.com/maps/api/js?key=<%= ENV['GOOGLE_MAPS_KEY'] %>"></script>
    <script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
    <script src="//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js" type="text/javascript"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  </head>

  <body>
    <div>
      <%= render 'layouts/navbar' %>
      <%= render 'shared/flash' %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/mail_form/contact.erb
<h4 style="text-decoration:underline"><%= message.subject %></h4>

<% @resource.mail_form_attributes.each do |attribute, value|
  next if value.blank? %>

  <p><b><%= @resource.class.human_attribute_name(attribute) %>:</b>
  <%= case value
    when /\n/
      raw(simple_format(h(value)))
    when Time, DateTime, Date
      I18n.l(value)
    else
      value
    end
  %></p>
<% end %>

<% unless @resource.class.mail_appendable.blank? %>
  <br /><h4 style="text-decoration:underline"><%= I18n.t :title, :scope => [ :mail_form, :request ], :default => 'Request information' %></h4>

  <% @resource.class.mail_appendable.each do |attribute|
    value = @resource.request.send(attribute)
    value = if value.is_a?(Hash) && !value.empty?
      list = value.to_a.map{ |k,v| content_tag(:li, h("#{k}: #{v.inspect}")) }.join("\n")
      content_tag(:ul, raw(list), :style => "list-style:none;")
    elsif value.is_a?(String)
      value
    else
      value.inspect
    end
  %>

    <p><b><%= I18n.t attribute, :scope => [ :mail_form, :request ], :default => attribute.to_s.humanize %>:</b>
    <%= value.include?("\n") ? simple_format(value) : value %></p>
  <% end %>
  <br />
<% end %>

app/views/shared/_flash.html.erb
<% flash.each do |key, value| %>
  <div class="<%= flash_class(key) %> alert-dismissable fade show" role="alert">
    <%= value %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>